repos:
  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.2.1
    hooks:
      - id: fmt
      - id: clippy
  - repo: local
    hooks:
      - id: lint
        name: mdlint
        language: system
        entry: uvx mdlint check
